/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Jesús
 */
public class jFrameCarreras extends javax.swing.JFrame {

    private C_Carrera controladorCarrera;
    private C_SQL controladorSQL;

    /**
     * Creates new form Carreras
     */
    public jFrameCarreras() {
        this.add(barra);
        initComponents();
        C_MiMenuBar menu = new C_MiMenuBar(this);
        this.setJMenuBar(menu.getBarraMenu());
        try {
            controladorSQL = new C_SQL(this);
            controladorSQL.mostrarCarreras();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jFrameCarreras.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setSize(702, 297);
        this.setResizable(false);
        jTableInscripcion.setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInscripcion = new javax.swing.JTable();
        jButtonParticipar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de Carreras");
        setMaximumSize(new java.awt.Dimension(702, 297));
        setMinimumSize(new java.awt.Dimension(702, 297));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableInscripcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Localidad", "Provincia", "Fecha", "Hora", "Distancia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableInscripcion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jTableInscripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 682, 184));

        jButtonParticipar.setText("Participar");
        jButtonParticipar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParticiparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonParticipar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pista-atletismo-superilla-poblenou-1490348978584.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonParticiparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParticiparActionPerformed
          if(jTableInscripcion.getSelectedRow() < 0)
            JOptionPane.showMessageDialog(this, "No hay ninguna fila seleccionada", "Error", JOptionPane.ERROR_MESSAGE);
        else{
             JOptionPane.showConfirmDialog(this, "¿Desea pagar la inscripción para participar en esta carrera?", "Confirmar participación", JOptionPane.INFORMATION_MESSAGE);
           }
    }//GEN-LAST:event_jButtonParticiparActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonParticipar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableInscripcion;
    // End of variables declaration//GEN-END:variables
   //conexión con la barra de navegación.
    C_MiMenuBar barra = new C_MiMenuBar(this);

    /**
     * Getter de la tabla
     * @return jTableInscripcion devuelve la tabla de al inscripción.
     */
    public JTable getjTableInscripcion() {
        return jTableInscripcion;
    }

}
